# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OHBM Sustainability and Environment Action Special Interest Group
email: ohbm.sea.sig@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The Sustainability and Environmental Action Special Interest Group (SEA-SIG)
  is a community-driven initiative under the Organisation for Human Brain Mapping
  (OHBM) dedicated to promoting environmental sustainability within the
  neuroimaging field.
github_username: ohbmenvironment
minimal_mistakes_skin: default
search: true
logo: assets/images/logo.png
masthead_title: OHBM Sustainability and Environment Action SIG
atom_feed:
  hide: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.27.3
# Outputting
permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# default author info
author:
  name   : "SEA-SIG member"
  avatar : "/assets/images/logo.png"
  bio    : "A member of the SEA-SIG committee."
  links:
    - label: "ohbm-environment.org"
      icon: "fas fa-fw fa-link"
      url: "https://ohbm-environment.org"
    - label: "ohbm.sea.sig@gmail.com"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ohbm.sea.sig@gmail.com"
    - label: "ohbmenvironment.bsky.social"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/ohbmenvironment.bsky.social"
    - label: "ohbmenvironment"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ohbmenvironment"

footer:
  since: 2020
  links:
    - label: "ohbm.sea.sig@gmail.com"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ohbm.sea.sig@gmail.com"
    - label: "ohbmenvironment.bsky.social"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/ohbmenvironment.bsky.social"
    - label: "ohbmenvironment"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ohbmenvironment"


social:
  type: Organization
  links:
    - "https://bsky.app/profile/ohbmenvironment.bsky.social"

defaults:
  - scope:
      path: "index.html"
    values:
      header:
        overlay_color: "#000"
        overlay_filter: "0.40"
        overlay_image: /assets/images/splash-image-brain.jpg
        actions:
          - label: "Interested? Join us on Mattermost!"
            url: "https://mattermost.ohbm-environment.org"
      excerpt: "Environmental sustainability for the neuroimaging community"
      working-groups:
        - title: "Annual meeting"
          image_path: assets/images/annual-meeting-wg.jpg
          excerpt: "Making the annual meeting sustainable and accessible by putting together engaging, impactful content."
          url: "/annual-meeting/"
          btn_label: "Learn More"
          btn_class: "btn--primary"  
        - title: "Green computing"
          image_path: /assets/images/green-computing-wg.jpg
          excerpt: "Reducing the footprint of neuroimaging data collection and analyses."
          url: "/neuroimaging-research-pipelines-group/"
          btn_label: "Learn More"
          btn_class: "btn--primary"
        - title: "Education and outreach"
          image_path: /assets/images/education-and-outreach-wg.jpg
          excerpt: "Producing year-round outreach materials."
          url: "/education/"
          btn_label: "Learn More"
          btn_class: "btn--primary"
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _pages/working-groups
  - scope:
      path: "_pages/working-groups"
    values:
      classes: wide
      sidebar:
        nav: "working-groups"
      header:
        overlay_color: "#000"
        overlay_filter: "0.40"
        overlay_image: /assets/images/splash-image-leaf.jpg
  # _pages/events
  - scope:
      path: "_pages/events"
    values:
      classes: wide
      sidebar:
        nav: "events"
      header:
        overlay_color: "#000"
        overlay_filter: "0.40"
        overlay_image: /assets/images/splash-image-map.png

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
